### ISSUE TITLE
Bug: Standard Context Menu lag when launched as admin (Menu bar or Tray icon)

### ISSUE THREAD

**Issue by AltF5** [winsiderss/systeminformer#1278]
### Brief description of your issue

Video demo of bug:
**https://www.youtube.com/watch?v=NkShxsJwrQA**

### Steps to reproduce

I'll attach this Debug64 build (unzip, rename .txt to .exe, verify im not trying to pwn you ... which I wouldn't based on how long i've been around here).
[SystemInformer.zip](https://github.com/winsiderss/systeminformer/files/8929020/SystemInformer.zip)

> Run elevated
> Click on the '**System**' menubar item (not View | Tools | Users | or Help which are Unaffected)
> Also impacted: Tray icon right clicking.

Does the lag occur to you with this build, or is it truly all my Win10 Machines & VMs when launched elevated ? (I don't have a Win11 VM at the moment to confirm). I don't quite understand how this would not be reproducible for you. This is occuring with the code downloaded as-is compiled in Debug | x64 as-is, with no settings, with no modifications, and attempted both in VS2022 and VS2022 Preview (both which compile fine, but experience this Menu bug).
**Can you try backing up and deleting your settings in %AppData%\Process Hacker just to be sure you don't have some setting that is preventing this?**

### Actual behavior
https://www.youtube.com/watch?v=NkShxsJwrQA

### Expected behavior
Function as intended. Not like that ^

### Environment

Win10 21H2.
Latest Windows SDK from VS2022 (did not ask for an upgrade, so nothing was changed)

**Comment by dmex** [comment]
I can't reproduce lag opening these menus... If anything your security software is screwing with bcd.dll and the registry BCD keys.

**Comment by AltF5** [comment]
@dmex sorry but this makes no sense (at least to me :) ) regarding **bcd.dll** and **registry BCD keys**
1. What does BCD and bcd.cpp have to do with the context menu generation (unless it is involved?) ?
2. Windows Defender is entirely disabled from the driver & kernel perspective on one of the PCs.
3. This can be repro-ed on multiple PCs, VMs, etc when running as an admin regardless of "security software

I'll attach this build (unzip, rename .txt to .exe, verify im not trying to pwn you ... which I wouldn't based on how long i've been around here)
[SystemInformer.zip](https://github.com/winsiderss/systeminformer/files/8928931/SystemInformer.zip)
"

**Comment by jxy-s** [comment]
I'm reopening this to continue the discussion/investigation. _**Do not**_ open a new issue just because a previous one (this one) was closed. _**Do not**_ mention/@ other maintainers to get attention on issues. This _is_ spamming.

@AltF5 I will follow up with a response to you in time. Please be patient.

**Comment by dmex** [comment]
> What does BCD and bcd.cpp in the code have to do with the standard context menu generation

The enumeration of boot entries for added to the shutdown menu under the System menu.

> This can be repro-ed on multiple PCs, VMs, etc when running as an admin regardless of "security software

I'm not seeing this on my machine or any other machines.

**Comment by AltF5** [comment]
> > What does BCD and bcd.cpp in the code have to do with the standard context menu generation
> 
> The enumeration of boot entries for added to the shutdown menu under the System menu.
> 
> > This can be repro-ed on multiple PCs, VMs, etc when running as an admin regardless of "security software
> 
> I'm not seeing this on my machine or any other machines.

Would this also impact the Tray Icon menu too... ? I guess it would if it contains the 'Computer' menu
Sorry for misunderstanding.
Strange this would impacts multiple PCs.

**Comment by jxy-s** [comment]
I too am unable to reproduce this on my machines. How you describe reproduction, both requiring admin and the tray/system menu, @dmex is likely correct about the boot entry enumeration. How many boot entries do you have?

**Comment by jxy-s** [comment]
If this is the problem we could probably init-once the lists in in `PhUiCreateComputerBootDeviceMenu` and `PhUiCreateComputerFirmwareDeviceMenu`. It might be wise to do that anyway since I do not believe those would change?

**Comment by diversenok** [comment]
I can reproduce a 0.5-second delay when running on the battery at 0.8 GHz. Indeed, it happens because of the queries to BCD that generate a few dozen IOCTLs per bootable drive and around 2k registry operations in total.

**Comment by AltF5** [comment]
> I too am unable to reproduce this on my machines. How you describe reproduction, both requiring admin and the tray/system menu, @dmex is likely correct about the boot entry enumeration. How many boot entries do you have?

C:\WINDOWS\system32>bcdedit

Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  partition=\Device\HarddiskVolume2
path                    \EFI\MICROSOFT\BOOT\BOOTMGFW.EFI
description             Windows Boot Manager
locale                  en-US
inherit                 {globalsettings}
default                 {current}
resumeobject            {87fa726e-49e5-11ec-be54-a78fb9474ed9}
displayorder            {current}
                        {ad479e7e-168c-11eb-8062-e4733c5fdc50}
                        {cd5538f6-a0fb-4212-9cf9-fbfa71061faa}
toolsdisplayorder       {memdiag}
timeout                 3

Windows Boot Loader
-------------------
identifier              {current}
device                  partition=C:
path                    \WINDOWS\system32\winload.efi
description             Windows 10
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {87fa7270-49e5-11ec-be54-a78fb9474ed9}
displaymessageoverride  Recovery
recoveryenabled         Yes
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \WINDOWS
resumeobject            {87fa726e-49e5-11ec-be54-a78fb9474ed9}
nx                      OptIn
bootmenupolicy          Standard

Windows Boot Loader
-------------------
identifier              {ad479e7e-168c-11eb-8062-e4733c5fdc50}
device                  partition=D:
path                    \WINDOWS\system32\winload.efi
description             G: Previous Windows
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {ad479e7f-168c-11eb-8062-e4733c5fdc50}
displaymessageoverride  Recovery
recoveryenabled         Yes
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=D:
systemroot              \WINDOWS
resumeobject            {16c754b9-6e95-11eb-80c6-806e6f6e6963}
nx                      OptIn
bootmenupolicy          Standard
useplatformclock        No
disabledynamictick      Yes

Windows Boot Loader
-------------------
identifier              {cd5538f6-a0fb-4212-9cf9-fbfa71061faa}
device                  partition=\Device\HarddiskVolume4
path                    \Windows\system32\winload.exe
description             (BCD on 970 Pro)
locale                  en-US
inherit                 {bootloadersettings}
bootdebug               No
osdevice                partition=\Device\HarddiskVolume4
systemroot              \Windows

**Comment by AltF5** [comment]
> If this is the problem we could probably init-once the lists in in `PhUiCreateComputerBootDeviceMenu` and `PhUiCreateComputerFirmwareDeviceMenu`. It might be wise to do that anyway since I do not believe those would change?

Fixed with commenting out line 2289 and 2290 mainwnd.c. Both are required to be removed
    PhInsertEMenuItem(menuItem, PhUiCreateComputerBootDeviceMenu(**DelayLoadMenu**), ULONG_MAX);
    PhInsertEMenuItem(menuItem, PhUiCreateComputerFirmwareDeviceMenu(**DelayLoadMenu**), ULONG_MAX);

https://github.com/winsiderss/systeminformer/blob/master/SystemInformer/mainwnd.c#L2289

Apologies @dmex for not understanding that BCD is being read for the Computer Shutdown menu.

**Comment by jxy-s** [comment]
@AltF5 will you please test this branch:

https://github.com/jxy-s/systeminformer/tree/init-once-firm-boot-lists

You will still have the one-time up-front cost of initializing it, but subsequent opens will be faster. If it works out for you I'll PR it.

**Comment by jxy-s** [comment]
I've closed it, it isn't an appropriate solution anyway.

**Comment by jxy-s** [comment]
@AltF5 you should still have a one-time up-front delay with the changes I made. But subsequent opens won't be slow. There is no way around that. Anyway, @dmex would like to keep it updated every time so it displays the most recent info for cases where users change the boot options.

We won't be addressing this.

**Comment by AltF5** [comment]
> @AltF5 you should still have a one-time up-front delay with the changes I made. But subsequent opens won't be slow. There is no way around that. Anyway, @dmex would like to keep it updated every time so it displays the most recent info for cases where users change the boot options.
> 
> We won't be addressing this.

OK, I'll make note to always remove these lines in my build. Thank you
```
    PhInsertEMenuItem(menuItem, PhUiCreateComputerBootDeviceMenu(DelayLoadMenu), ULONG_MAX);
    PhInsertEMenuItem(menuItem, PhUiCreateComputerFirmwareDeviceMenu(DelayLoadMenu), ULONG_MAX);
```

**Comment by jxy-s** [comment]
@AltF5 I that change so you don't have to maintain that yourself. There is an option in the advanced options to turn it off if you want to.
