### ISSUE TITLE
Changing the path to the debug symbols doesn't save on the Options window

### ISSUE THREAD

**Issue by trparky** [winsiderss/systeminformer#1402]
### Brief description of your issue

Changing the path to the debug symbols doesn't save on the Options window. The only way to make it stick is to enable Advanced Options and change it there but that's not exactly user friendly.

### Steps to reproduce (optional)

1. Open Options window.
2. Change path the debug symbols.
3. Close Options window.
4. Re-open Options window, notice how path to Symbols didn't save.

### Expected behavior (optional)

Obviously the path is saved.

### Environment (optional)

```shell
Nightly version, Windows 11 22H2.
```

**Comment by dmex** [comment]
This was already fixed 👍

**Comment by trparky** [comment]
Where? I don't see that as a fixed issue. I still have the issue and I've pulled down the latest source code from the master branch and compiled the program myself.

**Comment by dmex** [comment]
> I don't see that as a fixed issue.

I've been adding a new symbols options tab in settings which wasn't merged yet 👍
