### ISSUE TITLE
System Informer freezes as Admin (lazy load shutdown boot menu)

### ISSUE THREAD

**Issue by b1scu1t** [winsiderss/systeminformer#2141]
### Brief description of your issue

If System Informer is run as Admin, right-clicking the tray-icon or selecting the 'System' menu bar item in the window, will freeze the program for minutes to indefinitely. System Informer sometimes becomes impossible to kill by Task Manager, even when elevated.  

### Steps to reproduce (optional)

1. Launch System Informer as Admin
2. Right-click on the tray icon or hover the 'System' item in the menubar.

### Expected behavior (optional)

A sub-menu should appear.

### Actual behavior (optional)

System Informer freezes. Oddly enough, the tray icons would continue updating normally while SI froze. 

### Environment (optional)

```shell
System Informer 3.0.7660 (Stable) & 3.1.24192 (Canary)
Windows 10 LTSC IOT 2021 (Build: 19044.4651)
Windows 11 LTSC IOT 2024 (Build: ???)
```

**Comment by dmex** [comment]
> hover the 'System' item in the menubar.

There's a few different things named System. Are you referring to the System process or System Information?

> System Informer is run as Admin,

Do you have any extra characters in the window title + or ~?

**Comment by b1scu1t** [comment]
> > hover the 'System' item in the menubar.
> 
> There's a few different things named System. Are you referring to the System process or System Information?
> 
No. The System Informer's windows itself, in the menubar.
![image](https://github.com/user-attachments/assets/ffab3fc2-661d-4f04-be8e-3a7388c15a30)

> > System Informer is run as Admin,
> 
> Do you have any extra characters in the window title + or ~?

**Comment by dmex** [comment]
Can you open cmd.exe and copy the output from `bcdedit /v`?

**Comment by b1scu1t** [comment]
Somehow the `bcdedit /v` hangs?
![image](https://github.com/user-attachments/assets/040d5d28-a46a-4450-a883-48a8953b022d)
It showed this after 10 minutes. 

A busted BCD config? I re-installed Windows just last week with default settings...

**Comment by dmex** [comment]
> selecting the 'System' menu bar item in the window, will freeze the program for minutes to indefinitely. 

The system menu enumerates boot entries so you can restart directly into firmware or Windows Defender Offline Scan:  

![image](https://github.com/user-attachments/assets/00fef673-909d-4b2a-96df-69595e842771)

You'll need to fix bcdedit to resolve the issue with the System menu. 

> A busted BCD config? I re-installed Windows just last week with default settings...

If the system is booting correctly but bcdedit isn't working then there might be some issue with the partition:

https://superuser.com/questions/1261017/bcdedit-exe-refuses-to-open-system-store

**Comment by b1scu1t** [comment]
> > selecting the 'System' menu bar item in the window, will freeze the program for minutes to indefinitely.
> 
> The system menu enumerates boot entries so you can restart directly into firmware or Windows Defender Offline Scan:
> 
> ![image](https://private-user-images.githubusercontent.com/1306177/351927254-00fef673-909d-4b2a-96df-69595e842771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzIxNDQsIm5iZiI6MTcyMTg3MTg0NCwicGF0aCI6Ii8xMzA2MTc3LzM1MTkyNzI1NC0wMGZlZjY3My05MDlkLTRiMmEtOTZkZi02OTU5NWU4NDI3NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMDE0NDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUxZTJhMmJmYjVkNDc1NmEyMzZkNzJjNTNlMGQxZDA0YTY2ZmI0OWZmNTQwYTMxYTcyNTNhNmRiYjhmYzI0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NXbwZ3DsgOqtBb1r71BzRx7IMLXIN3UVFQ0JXm8W5fc)
> 
> You'll need to fix bcdedit to resolve the issue with the System menu.
> 
> > A busted BCD config? I re-installed Windows just last week with default settings...
> 
> If the system is booting correctly but bcdedit isn't working then there might be some issue with the partition:
> 
> https://superuser.com/questions/1261017/bcdedit-exe-refuses-to-open-system-store

That's exactly what I'm looking at right now. In any case, this isn't a SI bug. Sorry, should I close this?

**Comment by b1scu1t** [comment]
OK, the problem has been resolved. Just followed the instructions on [Minitool's site](https://www.partitionwizard.com/partitionmanager/the-boot-configuration-data-store-could-not-be-opened.html). Solutions 4 and 6 in particular, both in the Command Prompt of the Recovery Environment:


> # 4. Set an Entry Point in BCD
> Some users reported that the error can be solved by setting an entry point in BCD. It may seem strange but worth trying. Here’s how:
> 
> Step 1. Open the elevated Command Prompt window as we explained in the first solution.
> 
> Step 2. Type the following command and hit Enter. The /set command will set an entry point and enable the system to trust the Windows version that is not trusted by default.
> 
> bcdedit /set {current} Description “TheNameYouWant” 

*Replaced {current} with {default} in the Recovery Environment

> # 6. Rebuild BCD
> If none of the above methods fix the “bcdedit: The boot configuration data store could not be opened” error, you can consider manually rebuilding BCD in WinRE. To do so, you need to use the [Windows 10 media creation tool](https://www.partitionwizard.com/clone-disk/windows-10-media-creation-tool.html). Here’s how to do that:
> 
> Step 1. Plug the installation media into your computer and boot it from the media.
> 
> Step 2. Once started, click on Next > Repair your computer > Troubleshoot > Command Prompt in order.
> 
> Step 3. In the elevated Command Prompt window, type the following commands in order and hit Enter after each one.
> 
> bootrec /fixmbr
> bootrec /fixboot
> bootrec /scanos
> bootrec /rebuildbcd

`bootrec /fixboot` failed in my case, but every other command listed here worked. 
`bcdedit /enum` works now, and it listed the in Registry!
![image](https://github.com/user-attachments/assets/6595ffca-86ba-4ad1-a1ef-a17f2b946210)

Edit:...and it started failing again, when it worked just a while ago. I give up, Windows will give me a stroke.

**Comment by oddMLan** [comment]
Not fixed! I can fully reproduce the same hang except it's only a couple seconds long. Bcedit is normal on my end and it instantly enumarates the boot entries across my 3 disks. Using Windows 10 22H2.
![image](https://github.com/user-attachments/assets/0920b6dd-d2a1-4556-ba7f-07aade748188)
![image](https://github.com/user-attachments/assets/b76a46a2-7a80-4d4c-aa47-944357a27431)

The delay is very annoying.
Setting `EnableShutdownBootMenu` to 0 gets rid of the delay. Maybe you should lazy load the boot entries only as the user hovers on the shutdown boot menu, not every time one clicks on the 'System' menu.

**Comment by dmex** [comment]
> Setting EnableShutdownBootMenu to 0 gets rid of the delay. Maybe you should lazy load the boot entries only as the user hovers on the shutdown boot menu, not every time one clicks on the 'System' menu.

It's already lazy initialized. Windows also caches boot entries in the `HKEY_LOCAL_MACHINE\BCD00000000\Objects` registry key and we just enumerate these registry keys to show the current boot entries.

If there's a delay it's because something is preventing Windows from caching the `HKEY_LOCAL_MACHINE\BCD00000000\` keys.

**Comment by oddMLan** [comment]
I exported the registry key. Does it look normal?
[BCD00000000_Objects.reg.txt](https://github.com/user-attachments/files/16398337/BCD00000000_Objects.reg.txt)

**Comment by b1scu1t** [comment]
> Edit:...and it started failing again, when it worked just a while ago. I give up, Windows will give me a stroke.

Found the problem...it turns out that having a cheap-@$$ Micro Center SD card with a UEFI boot entry (E.g Ventoy) is enough to hang `bcdedit /enum`.  It looks for every UEFI boot capable device in the NVRAM, it seems??

Not sure if the SD card's crappy read/write speed is to blame or Ventoy's EFI being borked...the BIOS sees and boots it.

https://superuser.com/questions/1017398/bcdedit-is-having-big-time-delay
