### ISSUE TITLE
Efficiency "Save for ..." can only save "yes" state

### ISSUE THREAD

**Issue by Janmm14** [winsiderss/systeminformer#2212]
### Brief description of your issue

trying to ave a process to NOT be efficiency state does not work.
When "Save for ..." is ticked, and I am trying to untick "Set efficiency mode", on next update of System Informer theprocess will be set to efficiency mode again.

### Environment (optional)

```shell
Happened on stable.
I updated to preview 3.1.24258.0 Canary, still happening.

Windows 11 Pro 23H2
```

Every other "Save for ..." saves the current state and not just "yes" or not saved at all.

**Comment by Janmm14** [comment]
Every other "Save for ..." saves the state and not just "yes"

**Comment by dmex** [comment]
Fixed in latest nightly build

**Comment by Janmm14** [comment]
Not solved using "System Informer 3.1.24278.0 Canary"
efficiency "save as" checkmakr cannot be set without "efficiency" checked

**Comment by cylixlee** [comment]
I cannot save "no"-efficiency mode status too.

I unchecked the efficiency mode for msedge.exe, and clicked "Save for msedge.exe"; but when I launch the browser again, it's still in efficiency mode.
