### ISSUE TITLE
Pressing "Del" and confirming to kill process from the popup from the system tray icon crashes System Informer.

### ISSUE THREAD

**Issue by Max33Verstappen** [winsiderss/systeminformer#2336]
"Double-clicking, Enter" on the popup from the system tray icon brings up the main window of System Informer and it crashes. Pressing "Del" (in the popup) asks you if want to terminate a process and when press "yes", it also crashes.
![2024-12-16_10 06 20 277_explorer_Program_Manager](https://github.com/user-attachments/assets/0e88694b-c9c7-402c-96db-c2d7ec429501)
The last version that doesn't have this issue that I can download is "3.1.24244".

**Comment by ge0rdi** [comment]
I think this is the same issue as #2278 (that was closed prematurely).

**Comment by Max33Verstappen** [comment]
I found that pressing "del" and then confirming to terminate the selected process still crashes System Informer.
![395936697-0e88694b-c9c7-402c-96db-c2d7ec429501](https://github.com/user-attachments/assets/76fa163d-caec-421c-b7ac-da05c8b9b196)

**Comment by dmex** [comment]
Fixed in latest canary build

**Comment by Max33Verstappen** [comment]
Tried the latest "3.2.25051.101", but the crash still occurs.

**Comment by Max33Verstappen** [comment]
The crash occurs when I press the "Del" key outside of the miniinfo window, as it would let the miniinfo disappear. Then pressing "Terminate" leads to the crash.

**Comment by Max33Verstappen** [comment]
It's been fixed in the latest build. thanks.
