### ISSUE TITLE
Missing Resume button in MiniInfo's window context menu

### ISSUE THREAD

**Issue by Horse4Horse** [winsiderss/systeminformer#2681]
### Brief description of your issue

Context menu is missing "Resume" button.
Tedious to open main window and resume process from there.

![Image](https://github.com/user-attachments/assets/99271468-284f-4c6e-886a-c64e45bd4b55)

### Steps to reproduce (optional)

1. Open MiniInfo window
2. Select any process
3. Click RMB
4. Click "Suspend"
5. Refresh list
6. Click RMB on the same process

### Expected behavior (optional)

Context menu should display "Resume" option

### Actual behavior (optional)

Context menu does not have "Resume" option

### Environment (optional)

```shell
System Informer: 3.2.25011.2103
Windows 10 (19045.3930)
```

**Comment by dmex** [comment]
Fixed in latest canary build?

**Comment by Horse4Horse** [comment]
**System Informer 3.2.25263.221 (1ee8ec6e) Canary**:
The issue still persists

**Comment by dmex** [comment]
There is a resume button for the trayinfo window menu:
https://github.com/winsiderss/systeminformer/blob/8eeef3e97b92f03ae98395a9e0d91951307f6d44/SystemInformer/mainwnd.c#L4221-L4224

The TrayInfo window does not display suspended processes because it is specifically designed to show only the top X active processes. The value of X corresponds to the "Icon processes" setting found at the top of the General page in the Options window.

By default, TrayInfo displays a maximum of 15 processes. Since suspended processes do not consume system resources such as CPU time or system memory, they are not considered "active" and won't display in the top 15. As a result, they are excluded from the TrayInfo display and the "resume" button on the menu won't be displayed.

You'll need to use the main window or alternatively deselect the "Refresh automatically" option from the TrayInfo window menu so it doesn't remove suspended processes:

<img width="272" height="156" alt="Image" src="https://github.com/user-attachments/assets/c15ba80f-f00b-47e2-b269-24f5262cc98d" />

**Comment by Horse4Horse** [comment]
It does work as intended in the latest canary ( 3.2.25275.112 (6d779c43) ), even without changing any settings (I also tried setting "Icon processes" to 1 and it still displayed "resume" button) and with enabled auto-refresh.
![Image](https://github.com/user-attachments/assets/c3ce2925-3c8c-494c-b13a-e2ab09a2e296)

Changing "Icon processes" to any high number (4-8 digits) and disabling auto-refresh does not help on my older version (  3.2.25011.2103 (bfbd659b) ), so something was surely wrong with it
Seems like I have to update now, thanks for the help!
